title: sadra dadkhah
logo: /assets/img/1.jpg
email: sadra.dadkhah@gmail.com
description: hi welcome to my site
show_downloads: false
google_analytics: UA-108144808-1
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
